
export const mockTracks = [
    {
        id: '1',
        title: 'Bohemian Rhapsody',
        artist: 'Queen',
        album: 'A Night at the Opera',
        duration: 354,
        uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
        artwork: 'https://upload.wikimedia.org/wikipedia/en/4/4d/Queen_A_Night_At_The_Opera.png',
    },
    {
        id: '2',
        title: 'Hotel California',
        artist: 'Eagles',
        album: 'Hotel California',
        duration: 390,
        uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
        artwork: 'https://upload.wikimedia.org/wikipedia/en/4/49/Hotelcalifornia.jpg',
    },
    {
        id: '3',
        title: 'Imagine',
        artist: 'John Lennon',
        album: 'Imagine',
        duration: 183,
        uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
        artwork: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Imagine_cover.jpg',
    },
    {
        id: '4',
        title: 'Smells Like Teen Spirit',
        artist: 'Nirvana',
        album: 'Nevermind',
        duration: 301,
        uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
        artwork: 'https://upload.wikimedia.org/wikipedia/en/b/b7/NirvanaNevermindalbumcover.jpg',
    },
    {
        id: '5',
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        duration: 294,
        uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
        artwork: 'https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png',
    },
];